// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EQX4Sharp.Model
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

public enum EqxAttachmentType
{
    
    /// <remarks/>
    CalibrationSheet,
    
    /// <remarks/>
    DataSheet,
    
    /// <remarks/>
    Image,
}
}
#pragma warning restore
