// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EQX4Sharp.Model
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.Diagnostics.DebuggerStepThroughAttribute()]
public partial class EqxAddress
{
    
    #region Private fields
    private string _company;
    
    private string _contactName;
    
    private string _eMail;
    
    private string _phone;
    
    private string _fax;
    
    private string _street;
    
    private string _postCode;
    
    private string _city;
    
    private string _country;
    #endregion
    
    public string Company
    {
        get
        {
            return this._company;
        }
        set
        {
            this._company = value;
        }
    }
    
    public string ContactName
    {
        get
        {
            return this._contactName;
        }
        set
        {
            this._contactName = value;
        }
    }
    
    public string EMail
    {
        get
        {
            return this._eMail;
        }
        set
        {
            this._eMail = value;
        }
    }
    
    public string Phone
    {
        get
        {
            return this._phone;
        }
        set
        {
            this._phone = value;
        }
    }
    
    public string Fax
    {
        get
        {
            return this._fax;
        }
        set
        {
            this._fax = value;
        }
    }
    
    public string Street
    {
        get
        {
            return this._street;
        }
        set
        {
            this._street = value;
        }
    }
    
    public string PostCode
    {
        get
        {
            return this._postCode;
        }
        set
        {
            this._postCode = value;
        }
    }
    
    public string City
    {
        get
        {
            return this._city;
        }
        set
        {
            this._city = value;
        }
    }
    
    public string Country
    {
        get
        {
            return this._country;
        }
        set
        {
            this._country = value;
        }
    }
}
}
#pragma warning restore
