// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EQX4Sharp.Model
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

public enum EqxConnectorType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lemosa 1B")]
    Lemosa1B,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lemosa 2B")]
    Lemosa2B,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lemosa 4pol")]
    Lemosa4pol,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lemosa 8pol")]
    Lemosa8pol,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Amphenol 9pol")]
    Amphenol9pol,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Amphenol 79pol")]
    Amphenol79pol,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Amphenol 128pol")]
    Amphenol128pol,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Tajimi 5pol")]
    Tajimi5pol,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Tajimi 7pol flat")]
    Tajimi7polflat,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bendix 26pol")]
    Bendix26pol,
}
}
#pragma warning restore
