// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EQX4Sharp.Model
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.Diagnostics.DebuggerStepThroughAttribute()]
public partial class EqxCalHistoryEntry
{
    
    #region Private fields
    private long _calVersion;
    
    private EqxScalingMethod _scalingMethod;
    
    private float _sensitivity;
    
    private EqxEngineeringUnit _engineeringUnit;
    
    private double _sensitivity2;
    
    private double _sensitivity3;
    
    private double _sensitivity4;
    
    private double _sensitivity5;
    
    private float _sensitivityVoltage;
    
    private float _linearityDeviation;
    
    private float _standardDeviation;
    
    private float _hysteresisDeviation;
    
    private System.DateTime _calDate;
    
    private string _calPerson;
    
    private string _calLaboratory;
    
    private string _calInstruction;
    
    private string _calRemark;
    
    private bool _referenceCalibration;
    
    private List<System.Xml.XmlElement> _any;
    
    private List<EqxAttribute> _attribute;
    #endregion
    
    public EqxCalHistoryEntry()
    {
        this._attribute = new List<EqxAttribute>();
        this._any = new List<System.Xml.XmlElement>();
    }
    
    public long CalVersion
    {
        get
        {
            return this._calVersion;
        }
        set
        {
            this._calVersion = value;
        }
    }
    
    public EqxScalingMethod ScalingMethod
    {
        get
        {
            return this._scalingMethod;
        }
        set
        {
            this._scalingMethod = value;
        }
    }
    
    public float Sensitivity
    {
        get
        {
            return this._sensitivity;
        }
        set
        {
            this._sensitivity = value;
        }
    }
    
    public EqxEngineeringUnit EngineeringUnit
    {
        get
        {
            return this._engineeringUnit;
        }
        set
        {
            this._engineeringUnit = value;
        }
    }
    
    public double Sensitivity2
    {
        get
        {
            return this._sensitivity2;
        }
        set
        {
            this._sensitivity2 = value;
        }
    }
    
    public double Sensitivity3
    {
        get
        {
            return this._sensitivity3;
        }
        set
        {
            this._sensitivity3 = value;
        }
    }
    
    public double Sensitivity4
    {
        get
        {
            return this._sensitivity4;
        }
        set
        {
            this._sensitivity4 = value;
        }
    }
    
    public double Sensitivity5
    {
        get
        {
            return this._sensitivity5;
        }
        set
        {
            this._sensitivity5 = value;
        }
    }
    
    public float SensitivityVoltage
    {
        get
        {
            return this._sensitivityVoltage;
        }
        set
        {
            this._sensitivityVoltage = value;
        }
    }
    
    public float LinearityDeviation
    {
        get
        {
            return this._linearityDeviation;
        }
        set
        {
            this._linearityDeviation = value;
        }
    }
    
    public float StandardDeviation
    {
        get
        {
            return this._standardDeviation;
        }
        set
        {
            this._standardDeviation = value;
        }
    }
    
    public float HysteresisDeviation
    {
        get
        {
            return this._hysteresisDeviation;
        }
        set
        {
            this._hysteresisDeviation = value;
        }
    }
    
    public System.DateTime CalDate
    {
        get
        {
            return this._calDate;
        }
        set
        {
            this._calDate = value;
        }
    }
    
    public string CalPerson
    {
        get
        {
            return this._calPerson;
        }
        set
        {
            this._calPerson = value;
        }
    }
    
    public string CalLaboratory
    {
        get
        {
            return this._calLaboratory;
        }
        set
        {
            this._calLaboratory = value;
        }
    }
    
    public string CalInstruction
    {
        get
        {
            return this._calInstruction;
        }
        set
        {
            this._calInstruction = value;
        }
    }
    
    public string CalRemark
    {
        get
        {
            return this._calRemark;
        }
        set
        {
            this._calRemark = value;
        }
    }
    
    public bool ReferenceCalibration
    {
        get
        {
            return this._referenceCalibration;
        }
        set
        {
            this._referenceCalibration = value;
        }
    }
    
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public List<System.Xml.XmlElement> Any
    {
        get
        {
            return this._any;
        }
        set
        {
            this._any = value;
        }
    }
    
    public List<EqxAttribute> Attribute
    {
        get
        {
            return this._attribute;
        }
        set
        {
            this._attribute = value;
        }
    }
}
}
#pragma warning restore
