// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EQX4Sharp.Model
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

public enum EqxElectricalMethod
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Constant Current")]
    ConstantCurrent,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Full Bridge")]
    FullBridge,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Half Bridge")]
    HalfBridge,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Half Bridge Active")]
    HalfBridgeActive,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Quarter Bridge")]
    QuarterBridge,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Quarter Bridge Active")]
    QuarterBridgeActive,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Piezo Input")]
    PiezoInput,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Voltage Input")]
    VoltageInput,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Active Sensor")]
    ActiveSensor,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("UPS Data Logger")]
    UPSDataLogger,
}
}
#pragma warning restore
