// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EQX4Sharp.Model
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

public enum EqxPinFunction
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Positive Excitation Voltage")]
    PositiveExcitationVoltage,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Negative Excitation Voltage")]
    NegativeExcitationVoltage,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Positive Signal")]
    PositiveSignal,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Negative Signal")]
    NegativeSignal,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Positive Excitation Sense")]
    PositiveExcitationSense,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Negative Excitation Sense")]
    NegativeExcitationSense,
    
    /// <remarks/>
    Shielding,
    
    /// <remarks/>
    Ground,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Shunt Resistor")]
    ShuntResistor,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Identification Module")]
    IdentificationModule,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Combined Shunt and Identification")]
    CombinedShuntandIdentification,
}
}
#pragma warning restore
