// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.47. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace EQX4Sharp.Model
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.Diagnostics.DebuggerStepThroughAttribute()]
public partial class EqxSensorGroup : EqxBaseSensorGroup
{
    
    #region Private fields
    private EqxSensorGroupCategory _category;
    
    private string _name;
    
    private string _uUID;
    
    private string _serialNumber;
    
    private string _supplier;
    
    private string _model;
    
    private System.DateTime _calDate;
    
    private int _calPeriod;
    
    private string _calInfo;
    
    private int _useCount;
    
    private List<string> _path;
    #endregion
    
    public EqxSensorGroup()
    {
        this._path = new List<string>();
    }
    
    public EqxSensorGroupCategory Category
    {
        get
        {
            return this._category;
        }
        set
        {
            this._category = value;
        }
    }
    
    public string Name
    {
        get
        {
            return this._name;
        }
        set
        {
            this._name = value;
        }
    }
    
    public string UUID
    {
        get
        {
            return this._uUID;
        }
        set
        {
            this._uUID = value;
        }
    }
    
    public string SerialNumber
    {
        get
        {
            return this._serialNumber;
        }
        set
        {
            this._serialNumber = value;
        }
    }
    
    public string Supplier
    {
        get
        {
            return this._supplier;
        }
        set
        {
            this._supplier = value;
        }
    }
    
    public string Model
    {
        get
        {
            return this._model;
        }
        set
        {
            this._model = value;
        }
    }
    
    public System.DateTime CalDate
    {
        get
        {
            return this._calDate;
        }
        set
        {
            this._calDate = value;
        }
    }
    
    public int CalPeriod
    {
        get
        {
            return this._calPeriod;
        }
        set
        {
            this._calPeriod = value;
        }
    }
    
    public string CalInfo
    {
        get
        {
            return this._calInfo;
        }
        set
        {
            this._calInfo = value;
        }
    }
    
    public int UseCount
    {
        get
        {
            return this._useCount;
        }
        set
        {
            this._useCount = value;
        }
    }
    
    public List<string> Path
    {
        get
        {
            return this._path;
        }
        set
        {
            this._path = value;
        }
    }
}
}
#pragma warning restore
