//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EqxAttachmentType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="EqxAttachmentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CalibrationSheet"/>
 *     &lt;enumeration value="DataSheet"/>
 *     &lt;enumeration value="Image"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EqxAttachmentType")
@XmlEnum
public enum EqxAttachmentType {

	@XmlEnumValue("CalibrationSheet")
	CALIBRATION_SHEET("CalibrationSheet"), @XmlEnumValue("DataSheet")
	DATA_SHEET("DataSheet"), @XmlEnumValue("Image")
	IMAGE("Image");
	private final String value;

	EqxAttachmentType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static EqxAttachmentType fromValue(String v) {
		for (EqxAttachmentType c : EqxAttachmentType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
