//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.w3c.dom.Element;

/**
 * <p>
 * Java class for EqxCalHistoryEntry complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EqxCalHistoryEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CalVersion" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ScalingMethod" type="{}EqxScalingMethod" minOccurs="0"/>
 *         &lt;element name="Sensitivity" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="EngineeringUnit" type="{}EqxEngineeringUnit" minOccurs="0"/>
 *         &lt;element name="Sensitivity2" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Sensitivity3" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Sensitivity4" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Sensitivity5" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="SensitivityVoltage" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="LinearityDeviation" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="StandardDeviation" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="HysteresisDeviation" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="CalDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CalPerson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CalLaboratory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CalInstruction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CalRemark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceCalibration" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Attribute" type="{}EqxAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EqxCalHistoryEntry", propOrder = { "calVersion", "scalingMethod", "sensitivity", "engineeringUnit",
		"sensitivity2", "sensitivity3", "sensitivity4", "sensitivity5", "sensitivityVoltage", "linearityDeviation",
		"standardDeviation", "hysteresisDeviation", "calDate", "calPerson", "calLaboratory", "calInstruction",
		"calRemark", "referenceCalibration", "any", "attribute" })
@XmlSeeAlso({ EqxSensorAxis.class })
public class EqxCalHistoryEntry {

	@XmlElement(name = "CalVersion")
	protected Long calVersion;
	@XmlElement(name = "ScalingMethod")
	protected EqxScalingMethod scalingMethod;
	@XmlElement(name = "Sensitivity")
	protected Float sensitivity;
	@XmlElement(name = "EngineeringUnit")
	protected EqxEngineeringUnit engineeringUnit;
	@XmlElement(name = "Sensitivity2")
	protected Double sensitivity2;
	@XmlElement(name = "Sensitivity3")
	protected Double sensitivity3;
	@XmlElement(name = "Sensitivity4")
	protected Double sensitivity4;
	@XmlElement(name = "Sensitivity5")
	protected Double sensitivity5;
	@XmlElement(name = "SensitivityVoltage")
	protected Float sensitivityVoltage;
	@XmlElement(name = "LinearityDeviation")
	protected Float linearityDeviation;
	@XmlElement(name = "StandardDeviation")
	protected Float standardDeviation;
	@XmlElement(name = "HysteresisDeviation")
	protected Float hysteresisDeviation;
	@XmlElement(name = "CalDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar calDate;
	@XmlElement(name = "CalPerson")
	protected String calPerson;
	@XmlElement(name = "CalLaboratory")
	protected String calLaboratory;
	@XmlElement(name = "CalInstruction")
	protected String calInstruction;
	@XmlElement(name = "CalRemark")
	protected String calRemark;
	@XmlElement(name = "ReferenceCalibration")
	protected Boolean referenceCalibration;
	@XmlAnyElement(lax = true)
	protected List<Object> any;
	@XmlElement(name = "Attribute")
	protected List<EqxAttribute> attribute;

	/**
	 * Gets the value of the calVersion property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getCalVersion() {
		return calVersion;
	}

	/**
	 * Sets the value of the calVersion property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setCalVersion(Long value) {
		this.calVersion = value;
	}

	/**
	 * Gets the value of the scalingMethod property.
	 * 
	 * @return possible object is {@link EqxScalingMethod }
	 * 
	 */
	public EqxScalingMethod getScalingMethod() {
		return scalingMethod;
	}

	/**
	 * Sets the value of the scalingMethod property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxScalingMethod }
	 * 
	 */
	public void setScalingMethod(EqxScalingMethod value) {
		this.scalingMethod = value;
	}

	/**
	 * Gets the value of the sensitivity property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getSensitivity() {
		return sensitivity;
	}

	/**
	 * Sets the value of the sensitivity property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setSensitivity(Float value) {
		this.sensitivity = value;
	}

	/**
	 * Gets the value of the engineeringUnit property.
	 * 
	 * @return possible object is {@link EqxEngineeringUnit }
	 * 
	 */
	public EqxEngineeringUnit getEngineeringUnit() {
		return engineeringUnit;
	}

	/**
	 * Sets the value of the engineeringUnit property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxEngineeringUnit }
	 * 
	 */
	public void setEngineeringUnit(EqxEngineeringUnit value) {
		this.engineeringUnit = value;
	}

	/**
	 * Gets the value of the sensitivity2 property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getSensitivity2() {
		return sensitivity2;
	}

	/**
	 * Sets the value of the sensitivity2 property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setSensitivity2(Double value) {
		this.sensitivity2 = value;
	}

	/**
	 * Gets the value of the sensitivity3 property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getSensitivity3() {
		return sensitivity3;
	}

	/**
	 * Sets the value of the sensitivity3 property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setSensitivity3(Double value) {
		this.sensitivity3 = value;
	}

	/**
	 * Gets the value of the sensitivity4 property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getSensitivity4() {
		return sensitivity4;
	}

	/**
	 * Sets the value of the sensitivity4 property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setSensitivity4(Double value) {
		this.sensitivity4 = value;
	}

	/**
	 * Gets the value of the sensitivity5 property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getSensitivity5() {
		return sensitivity5;
	}

	/**
	 * Sets the value of the sensitivity5 property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setSensitivity5(Double value) {
		this.sensitivity5 = value;
	}

	/**
	 * Gets the value of the sensitivityVoltage property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getSensitivityVoltage() {
		return sensitivityVoltage;
	}

	/**
	 * Sets the value of the sensitivityVoltage property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setSensitivityVoltage(Float value) {
		this.sensitivityVoltage = value;
	}

	/**
	 * Gets the value of the linearityDeviation property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getLinearityDeviation() {
		return linearityDeviation;
	}

	/**
	 * Sets the value of the linearityDeviation property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setLinearityDeviation(Float value) {
		this.linearityDeviation = value;
	}

	/**
	 * Gets the value of the standardDeviation property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getStandardDeviation() {
		return standardDeviation;
	}

	/**
	 * Sets the value of the standardDeviation property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setStandardDeviation(Float value) {
		this.standardDeviation = value;
	}

	/**
	 * Gets the value of the hysteresisDeviation property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getHysteresisDeviation() {
		return hysteresisDeviation;
	}

	/**
	 * Sets the value of the hysteresisDeviation property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setHysteresisDeviation(Float value) {
		this.hysteresisDeviation = value;
	}

	/**
	 * Gets the value of the calDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getCalDate() {
		return calDate;
	}

	/**
	 * Sets the value of the calDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCalDate(XMLGregorianCalendar value) {
		this.calDate = value;
	}

	/**
	 * Gets the value of the calPerson property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCalPerson() {
		return calPerson;
	}

	/**
	 * Sets the value of the calPerson property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCalPerson(String value) {
		this.calPerson = value;
	}

	/**
	 * Gets the value of the calLaboratory property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCalLaboratory() {
		return calLaboratory;
	}

	/**
	 * Sets the value of the calLaboratory property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCalLaboratory(String value) {
		this.calLaboratory = value;
	}

	/**
	 * Gets the value of the calInstruction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCalInstruction() {
		return calInstruction;
	}

	/**
	 * Sets the value of the calInstruction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCalInstruction(String value) {
		this.calInstruction = value;
	}

	/**
	 * Gets the value of the calRemark property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCalRemark() {
		return calRemark;
	}

	/**
	 * Sets the value of the calRemark property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCalRemark(String value) {
		this.calRemark = value;
	}

	/**
	 * Gets the value of the referenceCalibration property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isReferenceCalibration() {
		return referenceCalibration;
	}

	/**
	 * Sets the value of the referenceCalibration property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setReferenceCalibration(Boolean value) {
		this.referenceCalibration = value;
	}

	/**
	 * Gets the value of the any property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the any property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAny().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Object }
	 * {@link Element }
	 * 
	 * 
	 */
	public List<Object> getAny() {
		if (any == null) {
			any = new ArrayList<Object>();
		}
		return this.any;
	}

	/**
	 * Gets the value of the attribute property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the attribute property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAttribute().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link EqxAttribute
	 * }
	 * 
	 * 
	 */
	public List<EqxAttribute> getAttribute() {
		if (attribute == null) {
			attribute = new ArrayList<EqxAttribute>();
		}
		return this.attribute;
	}

}
