//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EqxElectricalMethod.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="EqxElectricalMethod">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Constant Current"/>
 *     &lt;enumeration value="Full Bridge"/>
 *     &lt;enumeration value="Half Bridge"/>
 *     &lt;enumeration value="Half Bridge Active"/>
 *     &lt;enumeration value="Quarter Bridge"/>
 *     &lt;enumeration value="Quarter Bridge Active"/>
 *     &lt;enumeration value="Piezo Input"/>
 *     &lt;enumeration value="Voltage Input"/>
 *     &lt;enumeration value="Active Sensor"/>
 *     &lt;enumeration value="UPS Data Logger"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EqxElectricalMethod")
@XmlEnum
public enum EqxElectricalMethod {

	@XmlEnumValue("Constant Current")
	CONSTANT_CURRENT("Constant Current"), @XmlEnumValue("Full Bridge")
	FULL_BRIDGE("Full Bridge"), @XmlEnumValue("Half Bridge")
	HALF_BRIDGE("Half Bridge"), @XmlEnumValue("Half Bridge Active")
	HALF_BRIDGE_ACTIVE("Half Bridge Active"), @XmlEnumValue("Quarter Bridge")
	QUARTER_BRIDGE("Quarter Bridge"), @XmlEnumValue("Quarter Bridge Active")
	QUARTER_BRIDGE_ACTIVE("Quarter Bridge Active"), @XmlEnumValue("Piezo Input")
	PIEZO_INPUT("Piezo Input"), @XmlEnumValue("Voltage Input")
	VOLTAGE_INPUT("Voltage Input"), @XmlEnumValue("Active Sensor")
	ACTIVE_SENSOR("Active Sensor"), @XmlEnumValue("UPS Data Logger")
	UPS_DATA_LOGGER("UPS Data Logger");
	private final String value;

	EqxElectricalMethod(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static EqxElectricalMethod fromValue(String v) {
		for (EqxElectricalMethod c : EqxElectricalMethod.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
