//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for EqxFileInfo complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EqxFileInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DataFormatEdition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CreationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Software" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SoftwareVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EqxFileInfo")
public class EqxFileInfo {

	@XmlAttribute(name = "DataFormatEdition")
	protected String dataFormatEdition;
	@XmlAttribute(name = "CreationTime")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar creationTime;
	@XmlAttribute(name = "Software")
	protected String software;
	@XmlAttribute(name = "SoftwareVersion")
	protected String softwareVersion;

	/**
	 * Gets the value of the dataFormatEdition property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDataFormatEdition() {
		return dataFormatEdition;
	}

	/**
	 * Sets the value of the dataFormatEdition property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDataFormatEdition(String value) {
		this.dataFormatEdition = value;
	}

	/**
	 * Gets the value of the creationTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getCreationTime() {
		return creationTime;
	}

	/**
	 * Sets the value of the creationTime property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCreationTime(XMLGregorianCalendar value) {
		this.creationTime = value;
	}

	/**
	 * Gets the value of the software property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSoftware() {
		return software;
	}

	/**
	 * Sets the value of the software property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSoftware(String value) {
		this.software = value;
	}

	/**
	 * Gets the value of the softwareVersion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSoftwareVersion() {
		return softwareVersion;
	}

	/**
	 * Sets the value of the softwareVersion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSoftwareVersion(String value) {
		this.softwareVersion = value;
	}

}
