//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EqxSensors complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EqxSensors">
 *   &lt;complexContent>
 *     &lt;extension base="{}EqxBaseSensorGroup">
 *       &lt;sequence>
 *         &lt;element name="FileInfo" type="{}EqxFileInfo"/>
 *         &lt;element name="Owner" type="{}EqxAddress" minOccurs="0"/>
 *         &lt;element name="Sender" type="{}EqxAddress" minOccurs="0"/>
 *         &lt;element name="Recipient" type="{}EqxAddress" minOccurs="0"/>
 *         &lt;element name="OrderNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EqxSensors", propOrder = { "fileInfo", "owner", "sender", "recipient", "orderNumber" })
public class EqxSensors extends EqxBaseSensorGroup {

	@XmlElement(name = "FileInfo", required = true)
	protected EqxFileInfo fileInfo;
	@XmlElement(name = "Owner")
	protected EqxAddress owner;
	@XmlElement(name = "Sender")
	protected EqxAddress sender;
	@XmlElement(name = "Recipient")
	protected EqxAddress recipient;
	@XmlElement(name = "OrderNumber")
	protected String orderNumber;

	/**
	 * Gets the value of the fileInfo property.
	 * 
	 * @return possible object is {@link EqxFileInfo }
	 * 
	 */
	public EqxFileInfo getFileInfo() {
		return fileInfo;
	}

	/**
	 * Sets the value of the fileInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxFileInfo }
	 * 
	 */
	public void setFileInfo(EqxFileInfo value) {
		this.fileInfo = value;
	}

	/**
	 * Gets the value of the owner property.
	 * 
	 * @return possible object is {@link EqxAddress }
	 * 
	 */
	public EqxAddress getOwner() {
		return owner;
	}

	/**
	 * Sets the value of the owner property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxAddress }
	 * 
	 */
	public void setOwner(EqxAddress value) {
		this.owner = value;
	}

	/**
	 * Gets the value of the sender property.
	 * 
	 * @return possible object is {@link EqxAddress }
	 * 
	 */
	public EqxAddress getSender() {
		return sender;
	}

	/**
	 * Sets the value of the sender property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxAddress }
	 * 
	 */
	public void setSender(EqxAddress value) {
		this.sender = value;
	}

	/**
	 * Gets the value of the recipient property.
	 * 
	 * @return possible object is {@link EqxAddress }
	 * 
	 */
	public EqxAddress getRecipient() {
		return recipient;
	}

	/**
	 * Sets the value of the recipient property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxAddress }
	 * 
	 */
	public void setRecipient(EqxAddress value) {
		this.recipient = value;
	}

	/**
	 * Gets the value of the orderNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrderNumber() {
		return orderNumber;
	}

	/**
	 * Sets the value of the orderNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOrderNumber(String value) {
		this.orderNumber = value;
	}

}
