//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for EqxSensorAxis complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EqxSensorAxis">
 *   &lt;complexContent>
 *     &lt;extension base="{}EqxCalHistoryEntry">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ReadoutEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ConversionEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TedsType" type="{}EqxTedsType" minOccurs="0"/>
 *         &lt;element name="LocationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LocationLongname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyLongname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Supplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Technology" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExcitationVoltageMin" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ExcitationVoltageMax" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ElectricalMethod" type="{}EqxElectricalMethod" minOccurs="0"/>
 *         &lt;element name="PhysicalDimension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhysicalUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AxisDirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MinRange" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="MaxRange" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="MaxSensitivityDeviation" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="MaxLinearityDeviation" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="MaxStandardDeviation" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="MaxHysteresisDeviation" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Usable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IDModuleType" type="{}EqxIdModuleType" minOccurs="0"/>
 *         &lt;element name="IDModuleString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CalPeriod" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ShuntCheckPos" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShuntGainPos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ShuntValuePos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ShuntTolRelativePos" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ShuntCheckNeg" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShuntGainNeg" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ShuntValueNeg" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ShuntTolRelativeNeg" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ShuntResistance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="BridgeResistorPinpPexc" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="BridgeResistorPinpNexc" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="BridgeResistorNinpPexc" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="BridgeResistorNinpNexc" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="Offset" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="OffsetTol" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="OffsetCheck" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ElectricalPolarity" type="{}EqxPolarity" minOccurs="0"/>
 *         &lt;element name="ConnectorPin" type="{}EqxPin" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ConnectorType" type="{}EqxConnectorType" minOccurs="0"/>
 *         &lt;element name="ConnectorId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CalHistory" type="{}EqxCalHistoryEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeviceChannelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MountingPolarity" type="{}EqxPolarity" minOccurs="0"/>
 *         &lt;element name="Remark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreferredRange" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="SampleFrequency" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ExcitationVoltage" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="OffsetCompensation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SWOffsetCompensation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SWOffsetCompensationType" type="{}EqxSWOffsetCompensationType" minOccurs="0"/>
 *         &lt;element name="SWOffsetCalculationStartSec" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="SWOffsetCalculationEndSec" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="SWOffsetFixValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="SWFilterClassType" type="{}EqxFilterClassType" minOccurs="0"/>
 *         &lt;element name="SWFilterAdHocFrequency" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ConstInReadOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ConstInValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FiringMode" type="{}EqxFiringMode" minOccurs="0"/>
 *         &lt;element name="FiringDelay" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FiringDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="FiringVoltageLimit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="FiringCurrentLimit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Attachment" type="{}EqxAttachment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EqxSensorAxis", propOrder = { "name", "uuid", "enabled", "readoutEnabled", "conversionEnabled",
		"tedsType", "locationCode", "locationLongname", "companyCode", "companyLongname", "supplier", "model",
		"technology", "excitationVoltageMin", "excitationVoltageMax", "electricalMethod", "physicalDimension",
		"physicalUnit", "axisDirection", "minRange", "maxRange", "maxSensitivityDeviation", "maxLinearityDeviation",
		"maxStandardDeviation", "maxHysteresisDeviation", "serialNumber", "usable", "status", "idModuleType",
		"idModuleString", "calPeriod", "shuntCheckPos", "shuntGainPos", "shuntValuePos", "shuntTolRelativePos",
		"shuntCheckNeg", "shuntGainNeg", "shuntValueNeg", "shuntTolRelativeNeg", "shuntResistance",
		"bridgeResistorPinpPexc", "bridgeResistorPinpNexc", "bridgeResistorNinpPexc", "bridgeResistorNinpNexc",
		"offset", "offsetTol", "offsetCheck", "electricalPolarity", "connectorPin", "connectorType", "connectorId",
		"calHistory", "deviceChannelName", "mountingPolarity", "remark", "preferredRange", "sampleFrequency",
		"excitationVoltage", "offsetCompensation", "swOffsetCompensation", "swOffsetCompensationType",
		"swOffsetCalculationStartSec", "swOffsetCalculationEndSec", "swOffsetFixValue", "swFilterClassType",
		"swFilterAdHocFrequency", "constInReadOnly", "constInValue", "firingMode", "firingDelay", "firingDuration",
		"firingVoltageLimit", "firingCurrentLimit", "attachment" })
public class EqxSensorAxis extends EqxCalHistoryEntry {

	@XmlElement(name = "Name", required = true)
	protected String name;
	@XmlElement(name = "UUID", required = true)
	protected String uuid;
	@XmlElement(name = "Enabled")
	protected Boolean enabled;
	@XmlElement(name = "ReadoutEnabled")
	protected Boolean readoutEnabled;
	@XmlElement(name = "ConversionEnabled")
	protected Boolean conversionEnabled;
	@XmlElement(name = "TedsType")
	protected EqxTedsType tedsType;
	@XmlElement(name = "LocationCode")
	protected String locationCode;
	@XmlElement(name = "LocationLongname")
	protected String locationLongname;
	@XmlElement(name = "CompanyCode")
	protected String companyCode;
	@XmlElement(name = "CompanyLongname")
	protected String companyLongname;
	@XmlElement(name = "Supplier")
	protected String supplier;
	@XmlElement(name = "Model")
	protected String model;
	@XmlElement(name = "Technology")
	protected String technology;
	@XmlElement(name = "ExcitationVoltageMin")
	protected Float excitationVoltageMin;
	@XmlElement(name = "ExcitationVoltageMax")
	protected Float excitationVoltageMax;
	@XmlElement(name = "ElectricalMethod")
	protected EqxElectricalMethod electricalMethod;
	@XmlElement(name = "PhysicalDimension")
	protected String physicalDimension;
	@XmlElement(name = "PhysicalUnit")
	protected String physicalUnit;
	@XmlElement(name = "AxisDirection")
	protected String axisDirection;
	@XmlElement(name = "MinRange")
	protected Float minRange;
	@XmlElement(name = "MaxRange")
	protected Float maxRange;
	@XmlElement(name = "MaxSensitivityDeviation")
	protected Float maxSensitivityDeviation;
	@XmlElement(name = "MaxLinearityDeviation")
	protected Float maxLinearityDeviation;
	@XmlElement(name = "MaxStandardDeviation")
	protected Float maxStandardDeviation;
	@XmlElement(name = "MaxHysteresisDeviation")
	protected Float maxHysteresisDeviation;
	@XmlElement(name = "SerialNumber")
	protected String serialNumber;
	@XmlElement(name = "Usable")
	protected Boolean usable;
	@XmlElement(name = "Status")
	protected String status;
	@XmlElement(name = "IDModuleType")
	protected EqxIdModuleType idModuleType;
	@XmlElement(name = "IDModuleString")
	protected String idModuleString;
	@XmlElement(name = "CalPeriod")
	protected Integer calPeriod;
	@XmlElement(name = "ShuntCheckPos")
	protected Boolean shuntCheckPos;
	@XmlElement(name = "ShuntGainPos")
	protected Float shuntGainPos;
	@XmlElement(name = "ShuntValuePos")
	protected Float shuntValuePos;
	@XmlElement(name = "ShuntTolRelativePos")
	protected Float shuntTolRelativePos;
	@XmlElement(name = "ShuntCheckNeg")
	protected Boolean shuntCheckNeg;
	@XmlElement(name = "ShuntGainNeg")
	protected Float shuntGainNeg;
	@XmlElement(name = "ShuntValueNeg")
	protected Float shuntValueNeg;
	@XmlElement(name = "ShuntTolRelativeNeg")
	protected Float shuntTolRelativeNeg;
	@XmlElement(name = "ShuntResistance")
	protected Float shuntResistance;
	@XmlElement(name = "BridgeResistorPinpPexc")
	protected Float bridgeResistorPinpPexc;
	@XmlElement(name = "BridgeResistorPinpNexc")
	protected Float bridgeResistorPinpNexc;
	@XmlElement(name = "BridgeResistorNinpPexc")
	protected Float bridgeResistorNinpPexc;
	@XmlElement(name = "BridgeResistorNinpNexc")
	protected Float bridgeResistorNinpNexc;
	@XmlElement(name = "Offset")
	protected Float offset;
	@XmlElement(name = "OffsetTol")
	protected Float offsetTol;
	@XmlElement(name = "OffsetCheck")
	protected Boolean offsetCheck;
	@XmlElement(name = "ElectricalPolarity")
	protected EqxPolarity electricalPolarity;
	@XmlElement(name = "ConnectorPin")
	protected List<EqxPin> connectorPin;
	@XmlElement(name = "ConnectorType")
	protected EqxConnectorType connectorType;
	@XmlElement(name = "ConnectorId")
	protected String connectorId;
	@XmlElement(name = "CalHistory")
	protected List<EqxCalHistoryEntry> calHistory;
	@XmlElement(name = "DeviceChannelName")
	protected String deviceChannelName;
	@XmlElement(name = "MountingPolarity")
	protected EqxPolarity mountingPolarity;
	@XmlElement(name = "Remark")
	protected String remark;
	@XmlElement(name = "PreferredRange")
	protected Float preferredRange;
	@XmlElement(name = "SampleFrequency")
	protected Float sampleFrequency;
	@XmlElement(name = "ExcitationVoltage")
	protected Float excitationVoltage;
	@XmlElement(name = "OffsetCompensation")
	protected Boolean offsetCompensation;
	@XmlElement(name = "SWOffsetCompensation")
	protected Boolean swOffsetCompensation;
	@XmlElement(name = "SWOffsetCompensationType")
	protected EqxSWOffsetCompensationType swOffsetCompensationType;
	@XmlElement(name = "SWOffsetCalculationStartSec")
	protected Float swOffsetCalculationStartSec;
	@XmlElement(name = "SWOffsetCalculationEndSec")
	protected Float swOffsetCalculationEndSec;
	@XmlElement(name = "SWOffsetFixValue")
	protected Float swOffsetFixValue;
	@XmlElement(name = "SWFilterClassType")
	protected EqxFilterClassType swFilterClassType;
	@XmlElement(name = "SWFilterAdHocFrequency")
	protected Float swFilterAdHocFrequency;
	@XmlElement(name = "ConstInReadOnly")
	protected Boolean constInReadOnly;
	@XmlElement(name = "ConstInValue")
	protected Float constInValue;
	@XmlElement(name = "FiringMode")
	protected EqxFiringMode firingMode;
	@XmlElement(name = "FiringDelay")
	protected Float firingDelay;
	@XmlElement(name = "FiringDuration")
	protected Integer firingDuration;
	@XmlElement(name = "FiringVoltageLimit")
	protected Integer firingVoltageLimit;
	@XmlElement(name = "FiringCurrentLimit")
	protected Integer firingCurrentLimit;
	@XmlElement(name = "Attachment")
	protected List<EqxAttachment> attachment;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the uuid property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUUID() {
		return uuid;
	}

	/**
	 * Sets the value of the uuid property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUUID(String value) {
		this.uuid = value;
	}

	/**
	 * Gets the value of the enabled property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isEnabled() {
		return enabled;
	}

	/**
	 * Sets the value of the enabled property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setEnabled(Boolean value) {
		this.enabled = value;
	}

	/**
	 * Gets the value of the readoutEnabled property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isReadoutEnabled() {
		return readoutEnabled;
	}

	/**
	 * Sets the value of the readoutEnabled property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setReadoutEnabled(Boolean value) {
		this.readoutEnabled = value;
	}

	/**
	 * Gets the value of the conversionEnabled property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isConversionEnabled() {
		return conversionEnabled;
	}

	/**
	 * Sets the value of the conversionEnabled property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setConversionEnabled(Boolean value) {
		this.conversionEnabled = value;
	}

	/**
	 * Gets the value of the tedsType property.
	 * 
	 * @return possible object is {@link EqxTedsType }
	 * 
	 */
	public EqxTedsType getTedsType() {
		return tedsType;
	}

	/**
	 * Sets the value of the tedsType property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxTedsType }
	 * 
	 */
	public void setTedsType(EqxTedsType value) {
		this.tedsType = value;
	}

	/**
	 * Gets the value of the locationCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocationCode() {
		return locationCode;
	}

	/**
	 * Sets the value of the locationCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLocationCode(String value) {
		this.locationCode = value;
	}

	/**
	 * Gets the value of the locationLongname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocationLongname() {
		return locationLongname;
	}

	/**
	 * Sets the value of the locationLongname property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLocationLongname(String value) {
		this.locationLongname = value;
	}

	/**
	 * Gets the value of the companyCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * Sets the value of the companyCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompanyCode(String value) {
		this.companyCode = value;
	}

	/**
	 * Gets the value of the companyLongname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompanyLongname() {
		return companyLongname;
	}

	/**
	 * Sets the value of the companyLongname property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompanyLongname(String value) {
		this.companyLongname = value;
	}

	/**
	 * Gets the value of the supplier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * Sets the value of the supplier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSupplier(String value) {
		this.supplier = value;
	}

	/**
	 * Gets the value of the model property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModel() {
		return model;
	}

	/**
	 * Sets the value of the model property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModel(String value) {
		this.model = value;
	}

	/**
	 * Gets the value of the technology property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTechnology() {
		return technology;
	}

	/**
	 * Sets the value of the technology property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTechnology(String value) {
		this.technology = value;
	}

	/**
	 * Gets the value of the excitationVoltageMin property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getExcitationVoltageMin() {
		return excitationVoltageMin;
	}

	/**
	 * Sets the value of the excitationVoltageMin property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setExcitationVoltageMin(Float value) {
		this.excitationVoltageMin = value;
	}

	/**
	 * Gets the value of the excitationVoltageMax property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getExcitationVoltageMax() {
		return excitationVoltageMax;
	}

	/**
	 * Sets the value of the excitationVoltageMax property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setExcitationVoltageMax(Float value) {
		this.excitationVoltageMax = value;
	}

	/**
	 * Gets the value of the electricalMethod property.
	 * 
	 * @return possible object is {@link EqxElectricalMethod }
	 * 
	 */
	public EqxElectricalMethod getElectricalMethod() {
		return electricalMethod;
	}

	/**
	 * Sets the value of the electricalMethod property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxElectricalMethod }
	 * 
	 */
	public void setElectricalMethod(EqxElectricalMethod value) {
		this.electricalMethod = value;
	}

	/**
	 * Gets the value of the physicalDimension property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPhysicalDimension() {
		return physicalDimension;
	}

	/**
	 * Sets the value of the physicalDimension property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPhysicalDimension(String value) {
		this.physicalDimension = value;
	}

	/**
	 * Gets the value of the physicalUnit property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPhysicalUnit() {
		return physicalUnit;
	}

	/**
	 * Sets the value of the physicalUnit property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPhysicalUnit(String value) {
		this.physicalUnit = value;
	}

	/**
	 * Gets the value of the axisDirection property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAxisDirection() {
		return axisDirection;
	}

	/**
	 * Sets the value of the axisDirection property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAxisDirection(String value) {
		this.axisDirection = value;
	}

	/**
	 * Gets the value of the minRange property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMinRange() {
		return minRange;
	}

	/**
	 * Sets the value of the minRange property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMinRange(Float value) {
		this.minRange = value;
	}

	/**
	 * Gets the value of the maxRange property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMaxRange() {
		return maxRange;
	}

	/**
	 * Sets the value of the maxRange property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMaxRange(Float value) {
		this.maxRange = value;
	}

	/**
	 * Gets the value of the maxSensitivityDeviation property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMaxSensitivityDeviation() {
		return maxSensitivityDeviation;
	}

	/**
	 * Sets the value of the maxSensitivityDeviation property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMaxSensitivityDeviation(Float value) {
		this.maxSensitivityDeviation = value;
	}

	/**
	 * Gets the value of the maxLinearityDeviation property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMaxLinearityDeviation() {
		return maxLinearityDeviation;
	}

	/**
	 * Sets the value of the maxLinearityDeviation property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMaxLinearityDeviation(Float value) {
		this.maxLinearityDeviation = value;
	}

	/**
	 * Gets the value of the maxStandardDeviation property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMaxStandardDeviation() {
		return maxStandardDeviation;
	}

	/**
	 * Sets the value of the maxStandardDeviation property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMaxStandardDeviation(Float value) {
		this.maxStandardDeviation = value;
	}

	/**
	 * Gets the value of the maxHysteresisDeviation property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMaxHysteresisDeviation() {
		return maxHysteresisDeviation;
	}

	/**
	 * Sets the value of the maxHysteresisDeviation property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMaxHysteresisDeviation(Float value) {
		this.maxHysteresisDeviation = value;
	}

	/**
	 * Gets the value of the serialNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSerialNumber() {
		return serialNumber;
	}

	/**
	 * Sets the value of the serialNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSerialNumber(String value) {
		this.serialNumber = value;
	}

	/**
	 * Gets the value of the usable property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isUsable() {
		return usable;
	}

	/**
	 * Sets the value of the usable property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setUsable(Boolean value) {
		this.usable = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the idModuleType property.
	 * 
	 * @return possible object is {@link EqxIdModuleType }
	 * 
	 */
	public EqxIdModuleType getIDModuleType() {
		return idModuleType;
	}

	/**
	 * Sets the value of the idModuleType property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxIdModuleType }
	 * 
	 */
	public void setIDModuleType(EqxIdModuleType value) {
		this.idModuleType = value;
	}

	/**
	 * Gets the value of the idModuleString property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIDModuleString() {
		return idModuleString;
	}

	/**
	 * Sets the value of the idModuleString property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIDModuleString(String value) {
		this.idModuleString = value;
	}

	/**
	 * Gets the value of the calPeriod property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getCalPeriod() {
		return calPeriod;
	}

	/**
	 * Sets the value of the calPeriod property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setCalPeriod(Integer value) {
		this.calPeriod = value;
	}

	/**
	 * Gets the value of the shuntCheckPos property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isShuntCheckPos() {
		return shuntCheckPos;
	}

	/**
	 * Sets the value of the shuntCheckPos property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setShuntCheckPos(Boolean value) {
		this.shuntCheckPos = value;
	}

	/**
	 * Gets the value of the shuntGainPos property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getShuntGainPos() {
		return shuntGainPos;
	}

	/**
	 * Sets the value of the shuntGainPos property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setShuntGainPos(Float value) {
		this.shuntGainPos = value;
	}

	/**
	 * Gets the value of the shuntValuePos property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getShuntValuePos() {
		return shuntValuePos;
	}

	/**
	 * Sets the value of the shuntValuePos property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setShuntValuePos(Float value) {
		this.shuntValuePos = value;
	}

	/**
	 * Gets the value of the shuntTolRelativePos property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getShuntTolRelativePos() {
		return shuntTolRelativePos;
	}

	/**
	 * Sets the value of the shuntTolRelativePos property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setShuntTolRelativePos(Float value) {
		this.shuntTolRelativePos = value;
	}

	/**
	 * Gets the value of the shuntCheckNeg property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isShuntCheckNeg() {
		return shuntCheckNeg;
	}

	/**
	 * Sets the value of the shuntCheckNeg property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setShuntCheckNeg(Boolean value) {
		this.shuntCheckNeg = value;
	}

	/**
	 * Gets the value of the shuntGainNeg property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getShuntGainNeg() {
		return shuntGainNeg;
	}

	/**
	 * Sets the value of the shuntGainNeg property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setShuntGainNeg(Float value) {
		this.shuntGainNeg = value;
	}

	/**
	 * Gets the value of the shuntValueNeg property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getShuntValueNeg() {
		return shuntValueNeg;
	}

	/**
	 * Sets the value of the shuntValueNeg property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setShuntValueNeg(Float value) {
		this.shuntValueNeg = value;
	}

	/**
	 * Gets the value of the shuntTolRelativeNeg property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getShuntTolRelativeNeg() {
		return shuntTolRelativeNeg;
	}

	/**
	 * Sets the value of the shuntTolRelativeNeg property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setShuntTolRelativeNeg(Float value) {
		this.shuntTolRelativeNeg = value;
	}

	/**
	 * Gets the value of the shuntResistance property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getShuntResistance() {
		return shuntResistance;
	}

	/**
	 * Sets the value of the shuntResistance property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setShuntResistance(Float value) {
		this.shuntResistance = value;
	}

	/**
	 * Gets the value of the bridgeResistorPinpPexc property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getBridgeResistorPinpPexc() {
		return bridgeResistorPinpPexc;
	}

	/**
	 * Sets the value of the bridgeResistorPinpPexc property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setBridgeResistorPinpPexc(Float value) {
		this.bridgeResistorPinpPexc = value;
	}

	/**
	 * Gets the value of the bridgeResistorPinpNexc property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getBridgeResistorPinpNexc() {
		return bridgeResistorPinpNexc;
	}

	/**
	 * Sets the value of the bridgeResistorPinpNexc property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setBridgeResistorPinpNexc(Float value) {
		this.bridgeResistorPinpNexc = value;
	}

	/**
	 * Gets the value of the bridgeResistorNinpPexc property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getBridgeResistorNinpPexc() {
		return bridgeResistorNinpPexc;
	}

	/**
	 * Sets the value of the bridgeResistorNinpPexc property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setBridgeResistorNinpPexc(Float value) {
		this.bridgeResistorNinpPexc = value;
	}

	/**
	 * Gets the value of the bridgeResistorNinpNexc property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getBridgeResistorNinpNexc() {
		return bridgeResistorNinpNexc;
	}

	/**
	 * Sets the value of the bridgeResistorNinpNexc property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setBridgeResistorNinpNexc(Float value) {
		this.bridgeResistorNinpNexc = value;
	}

	/**
	 * Gets the value of the offset property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getOffset() {
		return offset;
	}

	/**
	 * Sets the value of the offset property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setOffset(Float value) {
		this.offset = value;
	}

	/**
	 * Gets the value of the offsetTol property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getOffsetTol() {
		return offsetTol;
	}

	/**
	 * Sets the value of the offsetTol property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setOffsetTol(Float value) {
		this.offsetTol = value;
	}

	/**
	 * Gets the value of the offsetCheck property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isOffsetCheck() {
		return offsetCheck;
	}

	/**
	 * Sets the value of the offsetCheck property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOffsetCheck(Boolean value) {
		this.offsetCheck = value;
	}

	/**
	 * Gets the value of the electricalPolarity property.
	 * 
	 * @return possible object is {@link EqxPolarity }
	 * 
	 */
	public EqxPolarity getElectricalPolarity() {
		return electricalPolarity;
	}

	/**
	 * Sets the value of the electricalPolarity property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxPolarity }
	 * 
	 */
	public void setElectricalPolarity(EqxPolarity value) {
		this.electricalPolarity = value;
	}

	/**
	 * Gets the value of the connectorPin property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the connectorPin property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getConnectorPin().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link EqxPin }
	 * 
	 * 
	 */
	public List<EqxPin> getConnectorPin() {
		if (connectorPin == null) {
			connectorPin = new ArrayList<EqxPin>();
		}
		return this.connectorPin;
	}

	/**
	 * Gets the value of the connectorType property.
	 * 
	 * @return possible object is {@link EqxConnectorType }
	 * 
	 */
	public EqxConnectorType getConnectorType() {
		return connectorType;
	}

	/**
	 * Sets the value of the connectorType property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxConnectorType }
	 * 
	 */
	public void setConnectorType(EqxConnectorType value) {
		this.connectorType = value;
	}

	/**
	 * Gets the value of the connectorId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConnectorId() {
		return connectorId;
	}

	/**
	 * Sets the value of the connectorId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setConnectorId(String value) {
		this.connectorId = value;
	}

	/**
	 * Gets the value of the calHistory property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the calHistory property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCalHistory().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link EqxCalHistoryEntry }
	 * 
	 * 
	 */
	public List<EqxCalHistoryEntry> getCalHistory() {
		if (calHistory == null) {
			calHistory = new ArrayList<EqxCalHistoryEntry>();
		}
		return this.calHistory;
	}

	/**
	 * Gets the value of the deviceChannelName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceChannelName() {
		return deviceChannelName;
	}

	/**
	 * Sets the value of the deviceChannelName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeviceChannelName(String value) {
		this.deviceChannelName = value;
	}

	/**
	 * Gets the value of the mountingPolarity property.
	 * 
	 * @return possible object is {@link EqxPolarity }
	 * 
	 */
	public EqxPolarity getMountingPolarity() {
		return mountingPolarity;
	}

	/**
	 * Sets the value of the mountingPolarity property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxPolarity }
	 * 
	 */
	public void setMountingPolarity(EqxPolarity value) {
		this.mountingPolarity = value;
	}

	/**
	 * Gets the value of the remark property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * Sets the value of the remark property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRemark(String value) {
		this.remark = value;
	}

	/**
	 * Gets the value of the preferredRange property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getPreferredRange() {
		return preferredRange;
	}

	/**
	 * Sets the value of the preferredRange property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setPreferredRange(Float value) {
		this.preferredRange = value;
	}

	/**
	 * Gets the value of the sampleFrequency property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getSampleFrequency() {
		return sampleFrequency;
	}

	/**
	 * Sets the value of the sampleFrequency property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setSampleFrequency(Float value) {
		this.sampleFrequency = value;
	}

	/**
	 * Gets the value of the excitationVoltage property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getExcitationVoltage() {
		return excitationVoltage;
	}

	/**
	 * Sets the value of the excitationVoltage property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setExcitationVoltage(Float value) {
		this.excitationVoltage = value;
	}

	/**
	 * Gets the value of the offsetCompensation property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isOffsetCompensation() {
		return offsetCompensation;
	}

	/**
	 * Sets the value of the offsetCompensation property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOffsetCompensation(Boolean value) {
		this.offsetCompensation = value;
	}

	/**
	 * Gets the value of the swOffsetCompensation property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isSWOffsetCompensation() {
		return swOffsetCompensation;
	}

	/**
	 * Sets the value of the swOffsetCompensation property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setSWOffsetCompensation(Boolean value) {
		this.swOffsetCompensation = value;
	}

	/**
	 * Gets the value of the swOffsetCompensationType property.
	 * 
	 * @return possible object is {@link EqxSWOffsetCompensationType }
	 * 
	 */
	public EqxSWOffsetCompensationType getSWOffsetCompensationType() {
		return swOffsetCompensationType;
	}

	/**
	 * Sets the value of the swOffsetCompensationType property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxSWOffsetCompensationType }
	 * 
	 */
	public void setSWOffsetCompensationType(EqxSWOffsetCompensationType value) {
		this.swOffsetCompensationType = value;
	}

	/**
	 * Gets the value of the swOffsetCalculationStartSec property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getSWOffsetCalculationStartSec() {
		return swOffsetCalculationStartSec;
	}

	/**
	 * Sets the value of the swOffsetCalculationStartSec property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setSWOffsetCalculationStartSec(Float value) {
		this.swOffsetCalculationStartSec = value;
	}

	/**
	 * Gets the value of the swOffsetCalculationEndSec property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getSWOffsetCalculationEndSec() {
		return swOffsetCalculationEndSec;
	}

	/**
	 * Sets the value of the swOffsetCalculationEndSec property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setSWOffsetCalculationEndSec(Float value) {
		this.swOffsetCalculationEndSec = value;
	}

	/**
	 * Gets the value of the swOffsetFixValue property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getSWOffsetFixValue() {
		return swOffsetFixValue;
	}

	/**
	 * Sets the value of the swOffsetFixValue property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setSWOffsetFixValue(Float value) {
		this.swOffsetFixValue = value;
	}

	/**
	 * Gets the value of the swFilterClassType property.
	 * 
	 * @return possible object is {@link EqxFilterClassType }
	 * 
	 */
	public EqxFilterClassType getSWFilterClassType() {
		return swFilterClassType;
	}

	/**
	 * Sets the value of the swFilterClassType property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxFilterClassType }
	 * 
	 */
	public void setSWFilterClassType(EqxFilterClassType value) {
		this.swFilterClassType = value;
	}

	/**
	 * Gets the value of the swFilterAdHocFrequency property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getSWFilterAdHocFrequency() {
		return swFilterAdHocFrequency;
	}

	/**
	 * Sets the value of the swFilterAdHocFrequency property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setSWFilterAdHocFrequency(Float value) {
		this.swFilterAdHocFrequency = value;
	}

	/**
	 * Gets the value of the constInReadOnly property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isConstInReadOnly() {
		return constInReadOnly;
	}

	/**
	 * Sets the value of the constInReadOnly property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setConstInReadOnly(Boolean value) {
		this.constInReadOnly = value;
	}

	/**
	 * Gets the value of the constInValue property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getConstInValue() {
		return constInValue;
	}

	/**
	 * Sets the value of the constInValue property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setConstInValue(Float value) {
		this.constInValue = value;
	}

	/**
	 * Gets the value of the firingMode property.
	 * 
	 * @return possible object is {@link EqxFiringMode }
	 * 
	 */
	public EqxFiringMode getFiringMode() {
		return firingMode;
	}

	/**
	 * Sets the value of the firingMode property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxFiringMode }
	 * 
	 */
	public void setFiringMode(EqxFiringMode value) {
		this.firingMode = value;
	}

	/**
	 * Gets the value of the firingDelay property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getFiringDelay() {
		return firingDelay;
	}

	/**
	 * Sets the value of the firingDelay property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setFiringDelay(Float value) {
		this.firingDelay = value;
	}

	/**
	 * Gets the value of the firingDuration property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getFiringDuration() {
		return firingDuration;
	}

	/**
	 * Sets the value of the firingDuration property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setFiringDuration(Integer value) {
		this.firingDuration = value;
	}

	/**
	 * Gets the value of the firingVoltageLimit property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getFiringVoltageLimit() {
		return firingVoltageLimit;
	}

	/**
	 * Sets the value of the firingVoltageLimit property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setFiringVoltageLimit(Integer value) {
		this.firingVoltageLimit = value;
	}

	/**
	 * Gets the value of the firingCurrentLimit property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getFiringCurrentLimit() {
		return firingCurrentLimit;
	}

	/**
	 * Sets the value of the firingCurrentLimit property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setFiringCurrentLimit(Integer value) {
		this.firingCurrentLimit = value;
	}

	/**
	 * Gets the value of the attachment property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the attachment property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAttachment().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link EqxAttachment
	 * }
	 * 
	 * 
	 */
	public List<EqxAttachment> getAttachment() {
		if (attachment == null) {
			attachment = new ArrayList<EqxAttachment>();
		}
		return this.attachment;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed property
	 * on this class.
	 * 
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 * 
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 * 
	 * 
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
