//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for EqxSensorGroup complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EqxSensorGroup">
 *   &lt;complexContent>
 *     &lt;extension base="{}EqxBaseSensorGroup">
 *       &lt;sequence>
 *         &lt;element name="Category" type="{}EqxSensorGroupCategory" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Supplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CalDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CalPeriod" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CalInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UseCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Path" type="{}EqxPath" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EqxSensorGroup", propOrder = { "category", "name", "uuid", "serialNumber", "supplier", "model",
		"calDate", "calPeriod", "calInfo", "useCount", "path" })
public class EqxSensorGroup extends EqxBaseSensorGroup {

	@XmlElement(name = "Category")
	protected EqxSensorGroupCategory category;
	@XmlElement(name = "Name", required = true)
	protected String name;
	@XmlElement(name = "UUID", required = true)
	protected String uuid;
	@XmlElement(name = "SerialNumber")
	protected String serialNumber;
	@XmlElement(name = "Supplier")
	protected String supplier;
	@XmlElement(name = "Model")
	protected String model;
	@XmlElement(name = "CalDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar calDate;
	@XmlElement(name = "CalPeriod")
	protected Integer calPeriod;
	@XmlElement(name = "CalInfo")
	protected String calInfo;
	@XmlElement(name = "UseCount")
	protected Integer useCount;
	@XmlElement(name = "Path")
	protected EqxPath path;

	/**
	 * Gets the value of the category property.
	 * 
	 * @return possible object is {@link EqxSensorGroupCategory }
	 * 
	 */
	public EqxSensorGroupCategory getCategory() {
		return category;
	}

	/**
	 * Sets the value of the category property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxSensorGroupCategory }
	 * 
	 */
	public void setCategory(EqxSensorGroupCategory value) {
		this.category = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the uuid property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUUID() {
		return uuid;
	}

	/**
	 * Sets the value of the uuid property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUUID(String value) {
		this.uuid = value;
	}

	/**
	 * Gets the value of the serialNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSerialNumber() {
		return serialNumber;
	}

	/**
	 * Sets the value of the serialNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSerialNumber(String value) {
		this.serialNumber = value;
	}

	/**
	 * Gets the value of the supplier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * Sets the value of the supplier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSupplier(String value) {
		this.supplier = value;
	}

	/**
	 * Gets the value of the model property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModel() {
		return model;
	}

	/**
	 * Sets the value of the model property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModel(String value) {
		this.model = value;
	}

	/**
	 * Gets the value of the calDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getCalDate() {
		return calDate;
	}

	/**
	 * Sets the value of the calDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCalDate(XMLGregorianCalendar value) {
		this.calDate = value;
	}

	/**
	 * Gets the value of the calPeriod property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getCalPeriod() {
		return calPeriod;
	}

	/**
	 * Sets the value of the calPeriod property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setCalPeriod(Integer value) {
		this.calPeriod = value;
	}

	/**
	 * Gets the value of the calInfo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCalInfo() {
		return calInfo;
	}

	/**
	 * Sets the value of the calInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCalInfo(String value) {
		this.calInfo = value;
	}

	/**
	 * Gets the value of the useCount property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getUseCount() {
		return useCount;
	}

	/**
	 * Sets the value of the useCount property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setUseCount(Integer value) {
		this.useCount = value;
	}

	/**
	 * Gets the value of the path property.
	 * 
	 * @return possible object is {@link EqxPath }
	 * 
	 */
	public EqxPath getPath() {
		return path;
	}

	/**
	 * Sets the value of the path property.
	 * 
	 * @param value
	 *            allowed object is {@link EqxPath }
	 * 
	 */
	public void setPath(EqxPath value) {
		this.path = value;
	}

}
