//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EqxSensorGroupCategory.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="EqxSensorGroupCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TestSetup"/>
 *     &lt;enumeration value="Dummy"/>
 *     &lt;enumeration value="Multi-Axis Sensor"/>
 *     &lt;enumeration value="TestBench"/>
 *     &lt;enumeration value="MeasurementDevice"/>
 *     &lt;enumeration value="Equipment"/>
 *     &lt;enumeration value="None"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EqxSensorGroupCategory")
@XmlEnum
public enum EqxSensorGroupCategory {

	@XmlEnumValue("TestSetup")
	TEST_SETUP("TestSetup"), @XmlEnumValue("Dummy")
	DUMMY("Dummy"), @XmlEnumValue("Multi-Axis Sensor")
	MULTI_AXIS_SENSOR("Multi-Axis Sensor"), @XmlEnumValue("TestBench")
	TEST_BENCH("TestBench"), @XmlEnumValue("MeasurementDevice")
	MEASUREMENT_DEVICE("MeasurementDevice"), @XmlEnumValue("Equipment")
	EQUIPMENT("Equipment"), @XmlEnumValue("None")
	NONE("None");
	private final String value;

	EqxSensorGroupCategory(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static EqxSensorGroupCategory fromValue(String v) {
		for (EqxSensorGroupCategory c : EqxSensorGroupCategory.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
