//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EqxScalingMethod.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="EqxScalingMethod">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Linear"/>
 *     &lt;enumeration value="Linear with Offset"/>
 *     &lt;enumeration value="IRTRACC"/>
 *     &lt;enumeration value="Cubic Polynomial"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EqxScalingMethod")
@XmlEnum
public enum EqxScalingMethod {

	@XmlEnumValue("Linear")
	LINEAR("Linear"), @XmlEnumValue("Linear with Offset")
	LINEAR_WITH_OFFSET("Linear with Offset"), IRTRACC("IRTRACC"), @XmlEnumValue("Cubic Polynomial")
	CUBIC_POLYNOMIAL("Cubic Polynomial");
	private final String value;

	EqxScalingMethod(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static EqxScalingMethod fromValue(String v) {
		for (EqxScalingMethod c : EqxScalingMethod.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
