//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:15:03 PM CET 
//

package com.github.eqx.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EqxSWOffsetCompensationType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="EqxSWOffsetCompensationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Pre test measurement"/>
 *     &lt;enumeration value="Average calculation"/>
 *     &lt;enumeration value="Fix value"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EqxSWOffsetCompensationType")
@XmlEnum
public enum EqxSWOffsetCompensationType {

	@XmlEnumValue("Pre test measurement")
	PRE_TEST_MEASUREMENT("Pre test measurement"), @XmlEnumValue("Average calculation")
	AVERAGE_CALCULATION("Average calculation"), @XmlEnumValue("Fix value")
	FIX_VALUE("Fix value");
	private final String value;

	EqxSWOffsetCompensationType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static EqxSWOffsetCompensationType fromValue(String v) {
		for (EqxSWOffsetCompensationType c : EqxSWOffsetCompensationType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
